services:
  devcontainer:
    build:
      dockerfile: ./Dockerfile
    command: /bin/sh -c "while sleep 1000; do :; done"
    environment:
      - MYSQL_DB=jakniedojade
      - MYSQL_USER=jakniedojade
      - MYSQL_PASSWORD=password
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
    volumes:
      - .:/jakniedojade
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend
    secrets:
      - waw_api_key
    stop_signal: SIGINT

  db:
    image: mariadb:11.4
    command: --max_allowed_packet=128M
    volumes:
      - mariadb_data:/var/lib/mysql:Z
    ports:
      - 3306:3306
    environment:
      - MARIADB_DATABASE=jakniedojade
      - MARIADB_USER=jakniedojade
      - MARIADB_PASSWORD=password
      - MARIADB_ROOT_PASSWORD=password
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - backend

volumes:
  mariadb_data:

networks:
  backend:

secrets:
  waw_api_key:
    file: waw_api_key.txt
