# Generated by Django 5.0.1 on 2024-06-29 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('route_short_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape_id', models.BigIntegerField()),
                ('point_sequency_number', models.IntegerField()),
                ('distance_traveled', models.FloatField()),
                ('point_latitude', models.FloatField()),
                ('point_longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('direction', models.BooleanField()),
                ('direction_headsign', models.CharField(blank=True, max_length=200, null=True)),
                ('shape_id', models.BigIntegerField(blank=True, null=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='latency_analyzer.route')),
            ],
        ),
        migrations.CreateModel(
            name='StopTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_sequence', models.IntegerField(blank=True, null=True)),
                ('arrival_time', models.TimeField()),
                ('on_demand', models.BooleanField(default=False)),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='latency_analyzer.stop')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='latency_analyzer.trip')),
            ],
        ),
        migrations.CreateModel(
            name='Latency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('latency', models.DurationField()),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='latency_analyzer.stop')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='latency_analyzer.trip')),
            ],
        ),
    ]
